apply plugin: 'com.android.application'

android {
    namespace 'com.example.localisationsmartphone'
    compileSdk 35

    defaultConfig {
        applicationId 'com.example.localisationsmartphone'
        minSdk 24
        targetSdk 35
        versionCode 1
        versionName '1.0'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'com.android.volley:volley:1.2.1'
}
